name: Clean assets

on:
  pull_request:
    paths:
      - src/assets/**

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-dependencies
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Clean assets
        if: ${{ !cancelled() }}
        run: pnpm clean-assets

      - name: Check if there are any changes
        id: verify_diff
        if: ${{ !cancelled() }}
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit lint fixes
        if: always() && steps.verify_diff.outputs.changed == 'true'
        run: |
          git commit -am "fix: clean assets" --no-verify
          git push
